version: '2.33.1'
services: 
  node-app: 
    build: 
      context: .
      target: production
      # args: 
      #   - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm run start




## you can use enviroment variables in the docker-compose file such as: 
    ## environment:
    ## - NODE_ENV=development ###
    
    